### PR TITLE
Option to submit DateRangePicker on change

### PR DESCRIPTION
**Pull request by SuperDicq**

### CODE REVIEW

**Comment by Nayjest** [comment]
Thanx for contribution. 
I reviewed your pull request.

1) You forget to declare is_submitted_on_change.

Please declare it as 
```php
protected $is_submitted_on_change = false;
```

(you can add commits to this pull request)

2) Why you perform an ajax request on submitting form? Can you explain following code?
```php
$('form').submit( function() {
    $.ajax({
        async: false,
        type: 'GET'
    });
});
```

**Comment by SuperDicq** [comment]
Simply ```$('form').submit()``` or an ```onchange="this.form.submit()"``` attribute somehow doesn't work in combination with the bootstrap daterangepicker. I couldn't find a better to get it working without adding an ajax request. 

I did indeed forget to commit ```protected $is_submitted_on_change = false;``` sorry about that.

**Comment by Nayjest** [comment]
>> Simply $('form').submit() or an onchange="this.form.submit()" attribute somehow doesn't work in combination with the bootstrap daterangepicker.

Looks like problem is related to selecting right form ( `$('form')` applies to all forms on page )

**Comment by SuperDicq** [comment]
There is usually only one form on the page which is created by the Grid. But you're right, there could be multiple forms on a page in a project.

In the select component you solved this using using ```onchange="this.form.submit()"```, but this does not work for the daterangepicker for some reason.

Do you have any suggestions?

**Comment by Nayjest** [comment]
Yep. I have suggestion. Try this:
```php
var update_hidden = function(ev, picker) {
            var $start = $('[name="<?= $component->getStartInputName() ?>"]');
            var $end =  $('[name="<?= $component->getEndInputName() ?>"]');
            $start.val(picker.startDate.format(options.format));
            $end.val(picker.endDate.format(options.format));
            <?php if(method_exists($component, 'isSubmittedOnChange') && $component->isSubmittedOnChange()): ?>
                $end.get(0).form.submit();
            <?php endif ?>
        };
```

Also please rename update_hidden function to something like onDatesChange becouse now it doesn't only updates hidden inputs.

And one more note: this view file is used *only* with DateRangePicker class therefore `method_exists($component, 'isSubmittedOnChange')` is not necessary, you can remote it.

**Comment by SuperDicq** [comment]
I did not try getting the right form using the name attribute yet.
I'll try this tomorrow, thanks for your help.

**Comment by SuperDicq** [comment]
I got it working using your suggestion.

**Comment by Nayjest** [comment]
Oh, great!
You forgot few '**;**' here:
```javascript
var start = $('[name="<?= $component->getStartInputName() ?>"]')
start.val(picker.startDate.format(options.format));
var end = $('[name="<?= $component->getEndInputName() ?>"]')
```

Please fix that and I will merge your pull-request (I can't fix that manually before merge becouse have no access to your branch).

**Comment by SuperDicq** [comment]
In Javascript semicolons are optional, but I'll add them for the sake of coherency.

**Comment by Nayjest** [comment]
I know :) Thanks.

**Comment by Nayjest** [comment]
Released in v0.9.12

**Pull request merged**
