### PR TITLE
Daterangepicker enhancement 

### PR DESCRIPTION
**Pull request by wdog**
adding the possibility to reset values

### CODE REVIEW

**Comment by Nayjest** [comment]
@wdog Thanks for this PR!
First of all, general recommendation: try to avoid adding changes not related to subject in pull-request (here is 5 files changed).

Before merging it:

1. Remove .idea from gitignore please. It's bad practice. You should add .idea to your global .gitignore (not related to any projects)
2. What is reason of moving hidden input in resources/views/default/grid.php? If there is any sense, move related comment from line 15 to input too and remove indent pefore input tag.
3. Regarding changes CsvExport:
I am afraid that replacing `use Paginator` to `Illuminate\Paginator\Paginator` may lead to issues.
Actually here is #140  
But problem is that your code makes impossible to use it with some paginator customizations because originally \Paginator is an alias of facade class (\Illuminate\Support\Facades\Paginator) and there may be class that differs from `Illuminate\Paginator\Paginator`  beyond facade. 
So, I think it would be better to replace it to `Illuminate\Support\Facades\Paginator` (if you have time to test it) or just revert changes in this files if you have no time for additional testing.

I don't know exactly how it works, but it's possible to add commits to your PR.

**Comment by wdog** [comment]
Thanks a lot for your useful tips!

Do you think that I can rollback everything and make a different pull request with only the daterangepicker? 

...then i'll try to test `Illuminate\Support\Facades\Paginator` for Csv and Excel

...and finally I'll try to find a solution for the form #132 , in order to use forms inside table cells

let me know if I'm on the rigth way. 
I'll also try to keep your indentation I'll promise :smile:

**Comment by wdog** [comment]
It is possible to delete this pull request or to hide or to disable?

**Comment by Nayjest** [comment]
Hi! Sure you can, but I think it would be easier just to add here commits with required changes.

**Comment by Nayjest** [comment]
Oh I see, you created another PR, ok, closing it.
Link: https://github.com/Nayjest/Grids/pull/145

**Pull request closed without merging**
