### PR TITLE
Adding Excel Export Component

### PR DESCRIPTION
**Pull request by alexonline82**
Add an Excel Export Component based on https://github.com/Maatwebsite/Laravel-Excel/tree/v2.0.2

### CODE REVIEW

**Comment by alexonline82** [comment]
the commit for hidden export fields are with errors. i will fix this in a few minutes. my problem is, that i need different fields on grid view and excel export

**Comment by Nayjest** [comment]
Do you really need that "isExportHidden" property for every column?
I suggest to add "is_hidden_columns_exported" property to Export component
( setter: setHiddenColumnsExported, getter: isHiddenColumnsExported  )

**Comment by Nayjest** [comment]
Upd: if you use ""isExportHidden"  to exclude columns from export (not to include hidden columns),  it would be better to add "ignored_columns" property to Export component.

**Comment by alexonline82** [comment]
For example, in front view i have the field "full user name" and in the export i need "firstname" and "lastname" and don't want to use field "full user name".

So i think i need "hideOnExport"

**Comment by Nayjest** [comment]
Ok then looks like you need both:
1. ExcelExport->ignored_columns = ['full_user_name']
2. ExcelExport->is_hidden_columns_exported = true  to include first_name & last_name columns that perhaps are hidden in grid becouse they are needed only for export and grid already contains full_user_name column

**Comment by alexonline82** [comment]
wait a minute, i will give it a try

**Comment by Nayjest** [comment]
Try master branch from my repo, I already pushed changes, is that implementation ok for you?

**Comment by Nayjest** [comment]
Whoops, looks like something went wrong. One moment please, I'll fix bugs

**Comment by Nayjest** [comment]
Fixed, try it

**Comment by Nayjest** [comment]
Note that you need to include "maatwebsite/excel" package to your app manually, I moved it from "require" to "suggest" section of composer.json becouse ExcelExport component not will be used in every grid.

**Comment by Nayjest** [comment]
Let me know if current implementation is ok, or make your suggestions and I will update readme & publish new release with ExcelExport component.

**Comment by Nayjest** [comment]
Also I have added to php_doc of ExcelExport.php
```php
/**
 * @author: Alexander Hofmeister
 */
```

:-)

**Comment by alexonline82** [comment]
Ah ok, i do the same things locally. But yours look much more beautiful ;-)

**Comment by Nayjest** [comment]
Thanx for great contribution!
Component published in release v0.7.9

If you will work on other common-usage components, share it :-)

**Pull request merged**
